<?php return array(
    'root' => array(
        'pretty_version' => '5.0.x-dev',
        'version' => '5.0.9999999.9999999-dev',
        'type' => 'library',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'reference' => 'f1962aea6529f255ef4d67990ba50ce17749213d',
        'name' => 'studip/core',
        'dev' => false,
    ),
    'versions' => array(
        'algo26-matthias/idna-convert' => array(
            'pretty_version' => 'v3.0.4',
            'version' => '3.0.4.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../algo26-matthias/idna-convert',
            'aliases' => array(),
            'reference' => '0786979b5ee8a8fee4731bd6d2be34490174bf74',
            'dev_requirement' => false,
        ),
        'beberlei/assert' => array(
            'pretty_version' => 'v2.9.9',
            'version' => '2.9.9.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../beberlei/assert',
            'aliases' => array(),
            'reference' => '124317de301b7c91d5fce34c98bba2c6925bec95',
            'dev_requirement' => false,
        ),
        'caxy/php-htmldiff' => array(
            'pretty_version' => 'v0.1.9',
            'version' => '0.1.9.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../caxy/php-htmldiff',
            'aliases' => array(),
            'reference' => '4bad5c6a4ecc76954d37764e6a29273b6b7bf1f8',
            'dev_requirement' => false,
        ),
        'davefx/phplot' => array(
            'pretty_version' => '6.2.1',
            'version' => '6.2.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../davefx/phplot',
            'aliases' => array(),
            'reference' => 'd2e201ecaabb0428116c89cebe281a8f54096450',
            'dev_requirement' => false,
        ),
        'ezyang/htmlpurifier' => array(
            'pretty_version' => 'v4.13.0',
            'version' => '4.13.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../ezyang/htmlpurifier',
            'aliases' => array(),
            'reference' => '08e27c97e4c6ed02f37c5b2b20488046c8d90d75',
            'dev_requirement' => false,
        ),
        'gossi/docblock' => array(
            'pretty_version' => 'v1.6',
            'version' => '1.6.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../gossi/docblock',
            'aliases' => array(),
            'reference' => 'd7e2f299279f5aebbfddeef1c119e26bef4bc7e9',
            'dev_requirement' => false,
        ),
        'guzzlehttp/psr7' => array(
            'pretty_version' => '1.4.2',
            'version' => '1.4.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/psr7',
            'aliases' => array(),
            'reference' => 'f5b8a8512e2b58b0071a7280e39f14f72e05d87c',
            'dev_requirement' => false,
        ),
        'jakeasmith/http_build_url' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../jakeasmith/http_build_url',
            'aliases' => array(),
            'reference' => '93c273e77cb1edead0cf8bcf8cd2003428e74e37',
            'dev_requirement' => false,
        ),
        'jasig/phpcas' => array(
            'pretty_version' => '1.3.8',
            'version' => '1.3.8.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../jasig/phpcas',
            'aliases' => array(),
            'reference' => '40c0769ce05a30c8172b36ceab11124375c8366e',
            'dev_requirement' => false,
        ),
        'kub-at/php-simple-html-dom-parser' => array(
            'pretty_version' => '1.9.1',
            'version' => '1.9.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kub-at/php-simple-html-dom-parser',
            'aliases' => array(),
            'reference' => 'ff22f98bfd9235115c128059076f3eb740d66913',
            'dev_requirement' => false,
        ),
        'mishal/iless' => array(
            'pretty_version' => '2.2.0',
            'version' => '2.2.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mishal/iless',
            'aliases' => array(),
            'reference' => 'd75af501ab0ca411efd041faa53e6652f1602553',
            'dev_requirement' => false,
        ),
        'neomerx/cors-psr7' => array(
            'pretty_version' => 'v1.0.13',
            'version' => '1.0.13.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../neomerx/cors-psr7',
            'aliases' => array(),
            'reference' => '2556e2013f16a55532c95928455257d5b6bbc6e2',
            'dev_requirement' => false,
        ),
        'neomerx/json-api' => array(
            'pretty_version' => 'v1.0.9',
            'version' => '1.0.9.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../neomerx/json-api',
            'aliases' => array(),
            'reference' => 'c911b7494496e79f9de72ee40d6a2b791caaf95b',
            'dev_requirement' => false,
        ),
        'nikic/fast-route' => array(
            'pretty_version' => 'v1.3.0',
            'version' => '1.3.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../nikic/fast-route',
            'aliases' => array(),
            'reference' => '181d480e08d9476e61381e04a71b34dc0432e812',
            'dev_requirement' => false,
        ),
        'opis/json-schema' => array(
            'pretty_version' => '1.1.0',
            'version' => '1.1.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../opis/json-schema',
            'aliases' => array(),
            'reference' => '39d8072be8657a329a284339994401066406c43b',
            'dev_requirement' => false,
        ),
        'paragonie/constant_time_encoding' => array(
            'pretty_version' => 'v2.3.0',
            'version' => '2.3.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../paragonie/constant_time_encoding',
            'aliases' => array(),
            'reference' => '47a1cedd2e4d52688eb8c96469c05ebc8fd28fa2',
            'dev_requirement' => false,
        ),
        'paragonie/random_compat' => array(
            'pretty_version' => 'v9.99.99',
            'version' => '9.99.99.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../paragonie/random_compat',
            'aliases' => array(),
            'reference' => '84b4dfb120c6f9b4ff7b3685f9b8f1aa365a0c95',
            'dev_requirement' => false,
        ),
        'phootwork/collection' => array(
            'pretty_version' => 'v1.6.1',
            'version' => '1.6.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phootwork/collection',
            'aliases' => array(),
            'reference' => '87def4453e84b98ce516d647bf23e4c497d4b95c',
            'dev_requirement' => false,
        ),
        'phootwork/lang' => array(
            'pretty_version' => 'v0.9',
            'version' => '0.9.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phootwork/lang',
            'aliases' => array(),
            'reference' => '752482b0c8f60d005414b0cb81646f72bf929724',
            'dev_requirement' => false,
        ),
        'phpseclib/phpseclib' => array(
            'pretty_version' => '2.0.31',
            'version' => '2.0.31.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpseclib/phpseclib',
            'aliases' => array(),
            'reference' => '233a920cb38636a43b18d428f9a8db1f0a1a08f4',
            'dev_requirement' => false,
        ),
        'phpxmlrpc/extras' => array(
            'pretty_version' => '0.6.2',
            'version' => '0.6.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpxmlrpc/extras',
            'aliases' => array(),
            'reference' => '327f1195feae4079c691fa281b7e63d2be4c193a',
            'dev_requirement' => false,
        ),
        'phpxmlrpc/phpxmlrpc' => array(
            'pretty_version' => '4.4.2',
            'version' => '4.4.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpxmlrpc/phpxmlrpc',
            'aliases' => array(),
            'reference' => '9b400d2c102f2a55839af8f73279274ebe148526',
            'dev_requirement' => false,
        ),
        'pimple/pimple' => array(
            'pretty_version' => 'v3.2.3',
            'version' => '3.2.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../pimple/pimple',
            'aliases' => array(),
            'reference' => '9e403941ef9d65d20cba7d54e29fe906db42cf32',
            'dev_requirement' => false,
        ),
        'psr/container' => array(
            'pretty_version' => '1.0.0',
            'version' => '1.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/container',
            'aliases' => array(),
            'reference' => 'b7ce3b176482dbbc1245ebf52b181af44c2cf55f',
            'dev_requirement' => false,
        ),
        'psr/http-message' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-message',
            'aliases' => array(),
            'reference' => 'f6561bf28d520154e4b0ec72be95418abe6d9363',
            'dev_requirement' => false,
        ),
        'psr/http-message-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/log' => array(
            'pretty_version' => '1.1.3',
            'version' => '1.1.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/log',
            'aliases' => array(),
            'reference' => '0f73288fd15629204f9d42b7055f72dacbe811fc',
            'dev_requirement' => false,
        ),
        'scssphp/scssphp' => array(
            'pretty_version' => 'v1.4.0',
            'version' => '1.4.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../scssphp/scssphp',
            'aliases' => array(),
            'reference' => 'f7c9088320e218ca42e4ef0074259a1ba24ec93a',
            'dev_requirement' => false,
        ),
        'slim/slim' => array(
            'pretty_version' => '3.12.3',
            'version' => '3.12.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../slim/slim',
            'aliases' => array(),
            'reference' => '1c9318a84ffb890900901136d620b4f03a59da38',
            'dev_requirement' => false,
        ),
        'spomky-labs/otphp' => array(
            'pretty_version' => 'v8.3.3',
            'version' => '8.3.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../spomky-labs/otphp',
            'aliases' => array(),
            'reference' => 'eb14442699ae6470b29ffd89238a9ccfb9f20788',
            'dev_requirement' => false,
        ),
        'studip/core' => array(
            'pretty_version' => '5.0.x-dev',
            'version' => '5.0.9999999.9999999-dev',
            'type' => 'library',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'reference' => 'f1962aea6529f255ef4d67990ba50ce17749213d',
            'dev_requirement' => false,
        ),
        'symfony/polyfill-ctype' => array(
            'pretty_version' => 'v1.18.1',
            'version' => '1.18.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-ctype',
            'aliases' => array(),
            'reference' => '1c302646f6efc070cd46856e600e5e0684d6b454',
            'dev_requirement' => false,
        ),
        'symfony/polyfill-mbstring' => array(
            'pretty_version' => 'v1.10.0',
            'version' => '1.10.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-mbstring',
            'aliases' => array(),
            'reference' => 'c79c051f5b3a46be09205c73b80b346e4153e494',
            'dev_requirement' => false,
        ),
        'symfony/polyfill-php56' => array(
            'pretty_version' => 'v1.18.1',
            'version' => '1.18.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php56',
            'aliases' => array(),
            'reference' => '13df84e91cd168f247c2f2ec82cc0fa24901c011',
            'dev_requirement' => false,
        ),
        'symfony/polyfill-util' => array(
            'pretty_version' => 'v1.18.1',
            'version' => '1.18.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-util',
            'aliases' => array(),
            'reference' => '46b910c71e9828f8ec2aa7a0314de1130d9b295a',
            'dev_requirement' => false,
        ),
        'symfony/yaml' => array(
            'pretty_version' => 'v3.4.46',
            'version' => '3.4.46.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/yaml',
            'aliases' => array(),
            'reference' => '88289caa3c166321883f67fe5130188ebbb47094',
            'dev_requirement' => false,
        ),
        'tecnickcom/tcpdf' => array(
            'pretty_version' => '6.3.5',
            'version' => '6.3.5.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../tecnickcom/tcpdf',
            'aliases' => array(),
            'reference' => '19a535eaa7fb1c1cac499109deeb1a7a201b4549',
            'dev_requirement' => false,
        ),
        'tuupola/cors-middleware' => array(
            'pretty_version' => '0.5.2',
            'version' => '0.5.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../tuupola/cors-middleware',
            'aliases' => array(),
            'reference' => 'db69d8e67b99570b16e8cd5f78c423ed1167cb21',
            'dev_requirement' => false,
        ),
    ),
);
